name       : assimp
version    : 4.1.0
release    : 2
source     :
    - https://github.com/assimp/assimp/archive/v4.1.0.tar.gz : 3520b1e9793b93a2ca3b797199e16f40d61762617e072f2d525fad70f9678a71
license    : BSD-3-Clause
component  : programming
summary    : Open Asset Import Library
description: |
    Open Asset Import Library
builddeps  :
    - gcc
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
