name       : assimp
version    : 3.3.1
release    : 1
source     :
    - https://github.com/assimp/assimp/archive/v3.3.1.tar.gz : d385c3f90876241343f09e45f4e5033a6a05861b971c63d1f6d512371ffdc7bf
license    : BSD-3-Clause
component  : programming
summary    : Open Asset Import Library
description: |
    Open Asset Import Library
builddeps  :
    - gcc
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
