name       : assimp
version    : 5.0.1
release    : 4
source     :
    - https://github.com/assimp/assimp/archive/v5.0.1.tar.gz : 11310ec1f2ad2cd46b95ba88faca8f7aaa1efe9aa12605c55e3de2b977b3dbfc
license    : BSD-3-Clause
component  : programming
summary    : Open Asset Import Library
description: |
    A library to import and export various 3d-model-formats including scene-post-processing to generate missing render data.
#builddeps  :
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
